project:
  type: website
  preview:
    port: 4200
  post-render:
    - julia ./_quarto/post-render.jl

author: "Dheepak Krishnamurthy"

website:
  title: "kdheepak"
  favicon: ./_quarto/favicon.svg
  search:
    location: navbar
  site-url: https://kdheepak.com
  repo-url: https://github.com/kdheepak/kdheepak.github.io
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    logo: _quarto/favicon.svg
    collapse: false
    search: true
    pinned: false
    left:
      - text: "About"
        href: ./index.qmd
      - text: "CV"
        href: ./cv/index.qmd
      - text: "Blog"
        href: ./blog/index.qmd
    right:
      - icon: rss
        href: index.xml
        aria-label: RSS
      - icon: github
        href: https://github.com/kdheepak
        aria-label: GitHub
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/dheepak-krishnamurthy
        rel: me
  sidebar:
    alignment: left
    style: docked
    collapse-level: 1
  page-footer:
    center:
      - text: "All views or opinions expressed here are solely mine and are not represented, shared, supported, or endorsed in any manner by any employer or entity."
format:
  html:
    grid:
      content-mode: standard
    theme:
      - pulse
      - ./_quarto/theme.scss
    css:
      - ./_quarto/styles.css
    mainfont: "Computer Modern Sans"
    code-copy: hover
    code-tools:
      source: repo
    highlight-style: printing
    include-in-header:
      - ./_quarto/font.html
      - ./_quarto/pre-language-script.html
    anchor-sections: true
    section-divs: true
    email-obfuscation: javascript
    html-q-tags: true
    toc: true
    toc-location: left
    toc-depth: 3
    shift-heading-level-by: 1
    number-sections: false
    callout-appearance: simple
    citations-hover: true
    cap-location: margin
    citation: true
    reference-location: margin
    from: markdown+emoji+mark
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/.*kdheepak\.com\/'
    code-block-border-left: true
    filters:
      - _quarto/alert.lua
      - code-visibility
      - collapse-callout
      - pseudocode
      - hide-comment
      - include-code-files
      - abstract-section
      - quarto
      - line-highlight
    comments:
      # hypothesis: true
      giscus:
        repo: kdheepak/kdheepak.github.io
        category: Comments
        reactions-enabled: true
        mapping: url

quarto-required: ">= 1.3.0"
links-as-notes: true
link-citations: true
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  eq-prefix: Equation

execute:
  cache: true
  output: true
  echo: true
  warning: true
  error: false
  freeze: true
  eval: true
  daemon: true

jupyter: julia-1.8

bibliography: ./_quarto/website.bib
csl: ./_quarto/ieee.csl
license: CC BY-SA
