[project]
name = "kdheepak.github.io"
version = "0.1.0"
description = "WEbsite"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyter = ">=1.0.0,<1.1"
