{
  "hash": "4e9aa6b3669823a787bf0a830f046ba6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Graphing CGP Grey's Rock-Paper-Scissors YouTube Game\ncategories:\n  - analysis\n  - python\nkeywords: python\ndate: '2023-10-23T04:21:19-0400'\n---\n\n\nIf you haven't already checked it out, go watch CGPGrey's Rock-Paper-Scissors YouTube Game.\n\n{{< video https://www.youtube.com/watch?v=PmWQmZXYd74 >}}\n\nIn this post, I'm going to explore what all the possible paths available are.\nLet's import some packages first.\n\n::: {#a1cd2767 .cell execution_count=2}\n``` {.julia .cell-code}\nusing PyCall\nusing Conda\nusing Graphs\nusing CairoMakie, GraphMakie\nusing GraphMakie.NetworkLayout\nusing JSON3\n```\n:::\n\n\nFortunately for us, CGPGrey was kind enough to put links to the choices in the\ndescription of (_almost_) every video.\nWe can use Google's YouTube API to get the video descriptions and get all the YouTube\nlinks in the description.\n\nWe are going to use the `google-api-python-client` in Python from Julia.\n\n::: {#d66db6b3 .cell execution_count=3}\n``` {.julia .cell-code code-fold=\"true\"}\nAPI_KEY = ENV[\"YOUTUBE_API_KEY\"]; # Get API_KEY from google console\nbuild = pyimport(\"googleapiclient.discovery\").build # from googleapiclient.discovery import build\nyoutube = build(\"youtube\", \"v3\", developerKey=API_KEY) # call build function in Python\n```\n\n::: {.cell-output .cell-output-display execution_count=58}\n```\nPyObject <googleapiclient.discovery.Resource object at 0x2b62a2280>\n```\n:::\n:::\n\n\nNow we can get the description of every video, extract the metadata from it into a `Dict` of `Dict`s, build a graph:\n\n::: {#78e05a07 .cell execution_count=4}\n``` {.julia .cell-code code-fold=\"true\"}\nyoutubeid(url) = string(first(split(replace(url, \"https://www.youtube.com/watch?v=\"=>\"\"), \"&t\")))\n\nfunction metadata(url)\n    id = youtubeid(url)\n    request = youtube.videos().list(part=\"snippet\", id=id)\n    response = request.execute()\n    description = response[\"items\"][1][\"snippet\"][\"description\"]\n    title = response[\"items\"][1][\"snippet\"][\"title\"]\n    if isempty(description)\n        # Special case for https://www.youtube.com/watch?v=CPb168NUwGc (description for this is empty)\n        return (; description = \"WIN: https://www.youtube.com/watch?v=RVLUX6BUEJI\\nLOSE / DRAW: https://www.youtube.com/watch?v=jDQqv3zkbIQ\\n\\n🌐 Website: https://www.cgpgrey.com\\n💖 Patreon: https://www.patreon.com/cgpgrey \\n📒 Cortex: http://www.cortexbrand.com\\n\\n\\n\\n\\n⛔️ Ah01F ✅\", title = \"🔴\")\n    end\n    (; description, title)\nend\n\nfunction links(url; visited=Dict(), duplicate_links = false)\n    m = metadata(url)\n    r = Dict(\n        :id => youtubeid(url),\n        :code => last(split(strip(m.description), \"\\n\")), # last line is a special code\n        :url => url,\n        :links => [],\n        :children => [],\n        :title => m.title\n    )\n    for line in split(m.description, \"\\n\")\n        if occursin(\"https://www.youtube.com/watch?v=\", line)\n            _status, video = split(line, \":\", limit=2)\n            video = strip(video)\n            push!(r[:links], Dict(:status => string(_status), :url => string(video)))\n        end\n    end\n\n    for link in r[:links]\n        url = link[:url]\n        if !(url in keys(visited))\n            visited[url] = Dict()\n            s = links(url; visited, duplicate_links)\n            push!(r[:children], s)\n            visited[url] = s\n        else\n            duplicate_links && push!(r[:children], visited[url])\n        end\n    end\n    return r\nend\n\nfunction cached_links(url; duplicate_links)\n    bfile = \"\"\"$(youtubeid(url))-$(duplicate_links ? \"dup-links\" : \"no-dup-links\").json\"\"\"\n    if isfile(bfile)\n        return JSON3.read(bfile)\n    end\n    r = links(url; duplicate_links)\n    open(bfile, \"w\") do f\n        JSON3.write(f, r)\n    end\n    r\nend\n\nfunction _clean_titles(str)\n  t = join([c for c in str if isascii(c)])\n  t = strip(t)\n  if occursin(\"Cortex\", t)\n      return \"\"\n  end\n  string(t)\nend\n\n\nfunction _node_builder(nodes, d)\n  for c in d[:children]\n    push!(nodes, (; id = c[:id], title = _clean_titles(c[:code]), url = c[:url]))\n    _node_builder(nodes, c)\n  end\nend\n\nfunction _graph_builder(G, d, ids)\n  from = d[:id]\n  for c in d[:children]\n    to = c[:id]\n    add_edge!(G, findfirst(isequal(from), ids), findfirst(isequal(to), ids))\n    _graph_builder(G, c, ids)\n  end\nend\n\nfunction get_nodes(data)\n  nodes = [(; id = data[:id], title = _clean_titles(data[:title]), url = data[:url])]\n  _node_builder(nodes, data)\n  nodes = unique(nodes)\n  ids = [n.id for n in nodes]\n  titles = [n.title for n in nodes]\n  urls = [n.url for n in nodes]\n  (; ids, titles, urls, nodes)\nend\n\nfunction grapher(data, ids)\n  G = SimpleDiGraph(length(ids))\n  _graph_builder(G, data, ids)\n  G\nend\n```\n:::\n\n\n::: {#8b07f535 .cell execution_count=5}\n``` {.julia .cell-code}\ndata = cached_links(\"https://www.youtube.com/watch?v=PmWQmZXYd74\", duplicate_links = true)\n(; ids, titles, urls, nodes) = get_nodes(data)\nG = grapher(data, ids)\n```\n\n::: {.cell-output .cell-output-display execution_count=60}\n```\n{111, 206} directed simple Int64 graph\n```\n:::\n:::\n\n\n::: {#dc30562a .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\nThere's **111** videos in the Graph with **206** connections between the videos.\n\n:::\n:::\n\n\nHere's what that graph visualized looks like:\n\n::: {#06848a11 .cell execution_count=7}\n``` {.julia .cell-code code-fold=\"true\"}\nempty_theme = Theme(\n    fonts=(; title = \"CMU Serif\"),\n)\n# If there's a space it is probably a unique name\nnode_colors = [length(split(strip(t))) > 1 ? :red : :black for t in titles]\nnode_size = [length(split(strip(t))) > 1 ? 8 : 5 for t in titles]\n\nf, ax, p = graphplot(G;\n    nlabels=titles,\n    nlabels_fontsize=5,\n    node_color=node_colors,\n    node_size,\n    arrow_size=10,\n    layout=Stress()\n)\nhidedecorations!(ax); hidespines!(ax);\n# offsets = [Point2f(0.1, -0.5) for _ in p[:node_pos][]]\n# offsets[1] = Point2f(0.1, 0.5)\n# p.nlabels_offset[] = offsets\nautolimits!(ax)\nax.title = \"CGP Grey's Rock-Paper-Scissors YouTube Game\"\nf\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n![](index_files/figure-html/cell-8-output-1.svg){}\n:::\n:::\n\n\nThis graph contains a lot of duplicate links to the same video.\nFor example when losing after different number of wins, you might end up at the same video.\nLet's remove those connections so we can visualize it as a tree.\n\n::: {#de32bc70 .cell execution_count=8}\n``` {.julia .cell-code code-fold=\"true\"}\ndata = cached_links(\"https://www.youtube.com/watch?v=PmWQmZXYd74\", duplicate_links = false)\n(; ids, titles, urls, nodes) = get_nodes(data)\nG = grapher(data, ids)\n```\n\n::: {.cell-output .cell-output-display execution_count=63}\n```\n{111, 110} directed simple Int64 graph\n```\n:::\n:::\n\n\n::: {#e9ddf8da .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\nThere's **111** videos in the Graph with **110** connections between the videos.\n\n:::\n:::\n\n\nHere's what the graph now visualized looks like:\n\n::: {#b9e11b70 .cell execution_count=10}\n``` {.julia .cell-code code-fold=\"true\"}\nempty_theme = Theme(\n    fonts=(; title = \"CMU Serif\"),\n)\n# If there's a space it is probably a unique name\nnode_colors = [length(split(strip(t))) > 1 ? :red : :black for t in titles]\nnode_size = [length(split(strip(t))) > 1 ? 8 : 5 for t in titles]\n\nf, ax, p = graphplot(G;\n    nlabels=titles,\n    nlabels_fontsize=10,\n    node_color=node_colors,\n    node_size,\n    arrow_size=8,\n    arrow_shift=:end,\n    layout=Buchheim()\n)\nhidedecorations!(ax); hidespines!(ax);\noffsets = [Point2f(0.1, -0.5) for _ in p[:node_pos][]]\noffsets[1] = Point2f(0.1, 0.5)\np.nlabels_offset[] = offsets\nautolimits!(ax)\nax.title = \"CGP Grey's Rock-Paper-Scissors YouTube Game\"\nf\n```\n\n::: {.cell-output .cell-output-display execution_count=65}\n![](index_files/figure-html/cell-11-output-1.svg){}\n:::\n:::\n\n\nThere we have it; a flowchart of the Rock-Paper-Scissors game.\n\nIf you liked this blog post, consider subscribing to\n[CGP Grey's Patreon](https://www.patreon.com/cgpgrey)\nso that they can make more awesome content like this.\n\nIf you are interested in viewing all the videos, you can check them out below:\n\n::: {#0e8718f3 .cell execution_count=11}\n``` {.julia .cell-code code-fold=\"true\"}\nusing IJulia\n\nfunction display_youtube_video(node)\n    video_id = split(node.url, \"=\")[end]\n    title = node.title\n    html_code = \"\"\"\n    <b>$(title)</b>\n    <br/>\n    <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/$video_id\" frameborder=\"0\" allowfullscreen></iframe>\n    \"\"\"\n    display(\"text/html\", HTML(html_code))\nend\n\n@assert unique(nodes) == nodes\ndisplay_youtube_video.(nodes);\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>One-in-a-Million YouTube Game: Can YOU Win?</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/PmWQmZXYd74\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h01W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Ul8r0Thgx44\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b></b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/_mrAeT9kpPM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h03W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/hoaLwPc571E\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h04W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/z8zjvT8Qx8U\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h05W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uHoYnV9JX4w\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h06W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/jRDLtKUsq8U\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h07W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RXy0Kc1Cl9s\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h08</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/v3oXQrWu-PA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h09W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/bN5M3caw6b8\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h10W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DDmnplXv6pY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h11W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/6auFOPOuHuE\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h12W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0M39bd9euEI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h13W    One Million Rock</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/E3pdr5hNBe4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Post Game Blue</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/s3rUNS68AKs\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Billion or Bust</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/K1kVsxsnYyc\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh14W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/wf6sqW38AmM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh15W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/j92TH0iaCrE\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh16W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/r8LgYG67bCA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh17W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DZLnWKM90nQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh18W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/aSjsXUdaIgQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh19W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/HunlKDzXNv0\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh19 5W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/gv7_NTC_Rgs\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh20W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/sbgMHxUkfFI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh21W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/4Nk29OAqZTw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh22W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/OjHzloSmLZg\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh23W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/I32ZGazBqWY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh24W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/-bGMZAWuL1o\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh25W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7GEmEWf1KgY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>RTh26W    Trillion End</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/4wUukNXczpM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Over a Billion, Under a Trillion</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/d0R5Csv7ogU\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Over a Million, Under a Billion</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/AgHpWh77STQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h13F    Paper</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YohvsF9mF3g\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h01W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RVLUX6BUEJI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h02W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/KHtDsZvsoMw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h03W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/t0hJIw19ChI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h04W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/e6zLBO0vez8\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h05W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/WR7AbrjBZNI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h06W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/fMyFx3bFW-s\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h07W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/hi4166mPpmA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h08W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/SxWZDOgaIog\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h09W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/-D_g1k0IzTQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h10W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/AnsaswKGPHk\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h11W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/8UKflLZq61E\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h12W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/tAcIxmJOA9o\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h12F - Rock</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/QxC-EQAsTuM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h01W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/b41_jrE8jFw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h02W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/oOufgnObuhQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h03W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/N7UCPssq-X8\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h04W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/FlwMxN9-mec\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h05W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ghJAsm9W3k0\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h06W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/55nbeaYL7hQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h07W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dB8-XaRclhk\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h08W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ddWvzSxz4AA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h09W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0xFOAtGBdUg\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h10W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/HSdwcDFDyQY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h11W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Q5kgEN3rb_c\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3h12W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/pteggMrRnk4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3 Rock</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/D8iP2qINaSE\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Post Game</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dU22iL1ZsWQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R3 Paper</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/hhDh6_RD7tU\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h13W    One Million Scissors</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/87zN8iWo5pU\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Really Over</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/LvcxrEP2U-o\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h13W    One Million Paper</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/yQKjsA90kpc\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2h12F    Scissors</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/_WKzx6tClQw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2xF PretFar</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7VmxQumJAL4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R2xF</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0odtRIBvjes\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h13F    Scissors</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/AGL2OMZzn2g\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1hPretFarF</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/yCwdjfzxI4I\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1hXF</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/qYaLoO40kjM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h03F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/r9-jSTCiHd0\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>R1h02F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/fWOtjGJvlGI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah01F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/CPb168NUwGc\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah02F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/jDQqv3zkbIQ\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah03F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/HXtheRKAkIw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah04F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/3qoxLsQ9464\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah05F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xjo-L59q8K4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah06F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dzK444eg53c\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Most Anti Lucky</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/LLZJ-U1UB5M\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah07F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/83hQScodfDA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>AntiEnd Under 1k</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/j-jqX7AdQT8\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah08F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/TFlsl2ZkBlI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah09F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/4ojQK570hDA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah10F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/WQ9wBn2Qk14\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah11F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/hT-25A8LFAE\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah12F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/e8zbuI-qJX4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah13F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xCb7UVssqlY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah14F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/54ZevZGGXZw\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah15F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/d84UbmiyBOs\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah16F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/X9jKHujmt1M\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah17F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/SeX6WzVRZ4Y\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah18F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/j8fHcBHeKwk\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>AntiEnd Over 1k</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/b6_QOYNf73g\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah19F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VtWv7m270kY\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah20F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/LSHMwceP0X8\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah21F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/BvL-kq_LLsI\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah22F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/KIcQP_OL0-0\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah23F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ei5WZihztGk\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah24F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/74E6BTyhv_c\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah25F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YnACGEG1tTc\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah26F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7Jp8Xp_9v90\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah27F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ILrJDLjx6sA\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah28F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/sJXuw8QM0W4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah29F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Gh_preEUg74\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah30F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YVJh73INvXk\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah31F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/9HDYmP-l_oM\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah32F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ugkWE2cy370\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah33F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/F-j5y5dyPDo\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah34F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/tlTOyDEZGUU\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah35W</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/wUjs_vVwh68\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<b>Ah35F</b>\n<br/>\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GG6AZGhLCS4\" frameborder=\"0\" allowfullscreen></iframe>\n```\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}