name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-latex-extra texlive-base texlive-fonts-extra pdf2svg imagemagick ghostscript graphviz
          version: 1.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo install svgbob_cli
          cargo install stork-search --locked
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install pdm
        run: pipx install pdm
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pdm install
      - uses: actions/setup-node@v2
      - name: Build
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb -O /tmp/pandoc.deb
          sudo dpkg -i /tmp/pandoc.deb
          pandoc --version
          node --version
          svgbob_cli --version
          python --version
          npm install
          NODE_ENV=production pdm run npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: main
          folder: build
          single-commit: true
