name: deploy
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.10.2
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install jupyter jupyter-client jupyter-cache

      - name: Install IJulia Conda
        run: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.add("Conda"); Pkg.instantiate(); Pkg.build()'

      - name: Run apt update and install
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-base texlive-fonts-extra texlive-luatex pdf2svg imagemagick ghostscript

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo installs
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/
          key: ${{ runner.os }}-cargo
      - name: Cargo install
        run: |
          cargo install svgbob_cli --force
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        if: steps.cache-cargo.outputs.cache-hit != 'true'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true

      - name: Check Quarto install
        run: quarto check install

      - name: Check Quarto kernels
        run: quarto check jupyter

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kdheepak
          directory: _site
